http.host: 0.0.0.0
config.reload.automatic: true
config.reload.interval: 10s
xpack.monitoring.elasticsearch.hosts:
- https://es01:9200
xpack.monitoring.enabled: false
monitoring.cluster_uuid: "6nDQoAmhTYCbShH-yPERZA"