# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: input
  path.config: "/usr/share/logstash/pipelines/input.conf"
- pipeline.id: alert
  path.config: "/usr/share/logstash/pipelines/alert.conf"
- pipeline.id: test
  path.config: "/usr/share/logstash/pipelines/logstash.conf"